version: '3.4'
services:
  fake-etsy-api:
    build:
      context: .
      target: local
    ports:
      - 8000-8000:8000-8000
    volumes:
      - /app/node_modules
      - .:/app
    command: yarn dev
    environment:
      - APPS=
